USE DATABASE DB;
USE SCHEMA STAGE_SCHEMA;

CREATE OR REPLACE STAGE CDC_EXSTAGE
STORAGE_INTEGRATION = CDC_EXSTAGE_INT --STORAGE INT THAT SNOWFLAKE WILL USE TO ACCESS MY S3 BUCKET
URL = 's3://cdc-pipeline-staging/landing/FullLoad/Customer/' --WHAT ALL FILES THIS EXT STAGE CAN REFER TO
FILE_FORMAT = (TYPE = 'PARQUET')